# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "044ee02dc2dbb9ae6f4f9b302681aee1"
name = "productlisting"
handle = "productlisting-3"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "quickstart-5961bd57.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
